[package]
name = "filmette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4.7", features = ["derive"]}
color-thief = "0.2.2"
home = "0.5.5"
image = "0.24.7"
